behaviors:
    PlayerBrain:
        trainer_type: ppo
        hyperparameters:
            batch_size: 32
            buffer_size: 2048
            learning_rate: 0.0003
            beta: 0.01
            epsilon: 0.2
            lambd: 0.95
            num_epoch: 3
            learning_rate_schedule: linear
        network_settings:
            normalize: false
            hidden_units: 128
            num_layers: 2
            memory:
                sequence_length: 32
                memory_size: 256
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            curiosity:
                gamma: 0.99
                strength: 0.01
                encoding_size: 256
                learning_rate: 0.0003
            gail:
                strength: 0.01
                gamma: 0.99
                encoding_size: 128
                demo_path: Demo.demo
                learning_rate: 0.0003
        keep_checkpoints: 5
        max_steps: 10000000
        time_horizon: 32
        summary_freq: 1000
        threaded: true